#!/bin/bash

# 🚀 GUIA RÁPIDO - DreamDirector AI

echo "╔══════════════════════════════════════════════════════════════╗"
echo "║         🎬 DreamDirector AI - Inicialização Rápida          ║"
echo "╚══════════════════════════════════════════════════════════════╝"
echo ""

echo "📋 OPÇÕES DISPONÍVEIS:"
echo ""
echo "1️⃣  Iniciar aplicação (Docker Compose)"
echo "   → ./start.sh"
echo ""
echo "2️⃣  Parar aplicação"
echo "   → ./stop.sh"
echo ""
echo "3️⃣  Ver logs em tempo real"
echo "   → docker compose logs -f"
echo ""
echo "4️⃣  Ver logs apenas do frontend"
echo "   → docker compose logs -f frontend"
echo ""
echo "5️⃣  Ver logs apenas do backend"
echo "   → docker compose logs -f backend"
echo ""
echo "6️⃣  Verificar status dos containers"
echo "   → docker compose ps"
echo ""
echo "7️⃣  Reiniciar aplicação"
echo "   → ./stop.sh && ./start.sh"
echo ""
echo "╔══════════════════════════════════════════════════════════════╗"
echo "║                         🌐 ACESSOS                           ║"
echo "╚══════════════════════════════════════════════════════════════╝"
echo ""
echo "  Frontend:  http://localhost:3000"
echo "  Backend:   http://localhost:8080"
echo "  Health:    http://localhost:8080/health"
echo ""
echo "╔══════════════════════════════════════════════════════════════╗"
echo "║                   📦 ESTRUTURA DO PROJETO                    ║"
echo "╚══════════════════════════════════════════════════════════════╝"
echo ""
echo "  videoclip-gen/"
echo "  ├── frontend/          → React + Vite (porta 3000)"
echo "  ├── backend/           → Express + FFmpeg (porta 8080)"
echo "  ├── start.sh           → Iniciar containers"
echo "  ├── stop.sh            → Parar containers"
echo "  ├── docker-compose.yml → Orquestração"
echo "  └── doc/               → Documentação"
echo ""
echo "╔══════════════════════════════════════════════════════════════╗"
echo "║                    ✅ PRÓXIMOS PASSOS                        ║"
echo "╚══════════════════════════════════════════════════════════════╝"
echo ""
echo "  1. Execute: ./start.sh"
echo "  2. Aguarde containers iniciarem (~30s)"
echo "  3. Acesse: http://localhost:3000"
echo "  4. Teste a aplicação"
echo "  5. Para parar: ./stop.sh"
echo ""
echo "╔══════════════════════════════════════════════════════════════╗"
echo "║                      🐛 TROUBLESHOOTING                      ║"
echo "╚══════════════════════════════════════════════════════════════╝"
echo ""
echo "  ❌ Porta já em uso?"
echo "     → docker compose down -v"
echo "     → sudo lsof -i :3000"
echo "     → sudo lsof -i :8080"
echo ""
echo "  ❌ Containers não iniciam?"
echo "     → docker compose logs"
echo "     → Verifique se FFmpeg está instalado"
echo ""
echo "  ❌ Frontend não conecta no backend?"
echo "     → Verifique http://localhost:8080/health"
echo "     → Inspecione logs: docker compose logs -f backend"
echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""

